version: '3.9'

networks: 
    tig-net:
        driver: bridge

volumes:
    tig-data:

services:
    influxdb:
        image: influxdb:1.8.10
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "${INFLUXDB_NAME}"
            INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER}"
            INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/influxdb

    grafana:
        image: grafana/grafana:8.2.6
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
            GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/grafana
        restart: always        

    telegraf:
        image: telegraf:1.25.3
        depends_on: 
            - "influxdb"
        # We explicit the .env file so that telegraf.conf can access the variables declared in it. 
        env_file:
          - .env
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "${INFLUXDB_NAME}"
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
        tty: true
        networks: 
            - tig-net
        privileged: true
